=== HibbaHindawi/wt3/U1/movielist.dtd
<!-- 
movielist
    category
    movie+
        title
        credits
            director
            writer
        description?
        score
        rating
        production
            date
                year
                month
                day
            budget
            country
        IMDb_website
            attr:url
    date
-->
<!ELEMENT movieList (category, movie+)>
    <!ELEMENT category (#PCDATA)>
    <!ELEMENT movie (title, credits, description?, score, rating, production, IMDb_website)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT credits (director+, writer+)>
            <!ELEMENT director (#PCDATA)>
            <!ELEMENT writer (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT score (#PCDATA)>
        <!ELEMENT rating (#PCDATA)>
        <!ELEMENT production (date, budget, country+)>
            <!ELEMENT date (year, month, day)>
                <!ELEMENT year (#PCDATA)>
                <!ELEMENT month (#PCDATA)>
                <!ELEMENT day (#PCDATA)>
            <!ELEMENT budget (#PCDATA)>
                <!ATTLIST budget currency (USD|RUB|SEK|GBP) #REQUIRED>
            <!ELEMENT country (#PCDATA)>
        <!ELEMENT IMDb_website EMPTY>
            <!ATTLIST IMDb_website url CDATA #REQUIRED>

=== HibbaHindawi/wt3/U1/movielist2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE movieList SYSTEM "movielist.dtd">

<movieList>
    
    <category>Science Fiction</category>

    <movie>
        <title>Interstellar</title>
        <credits>
            <director>Christopher Nolan</director>
            <writer>Jonathan Nolan</writer>
            <writer>Christopher Nolan</writer>
        </credits>
        <description>En grupp forskare och upptäcktsresande planerar att hitta en ny värld i en
            annan galax genom att färdas genom ett nyupptäckt maskhål nära Saturnus. Det blir det
            viktigaste uppdraget i mänsklighetens historia.</description>
        <score>8.7</score>
        <rating>PG-13</rating>
        <production>
            <date>
                <year>2014</year>
                <month>11</month>
                <day>07</day>
            </date>
            <budget currency="USD">165 miljoner</budget>
            <country>USA</country>
            <country>Storbritannien</country>
            <country>Kanada</country>
        </production>
        <IMDb_website url="https://www.imdb.com/title/tt0816692/" />
    </movie>

    <movie>
        <title>The Maze Runner</title>
        <credits>
            <director>Wes Ball</director>
            <writer>Noah Oppenheim</writer>
            <writer>Grant Pierce Myers</writer>
            <writer>T.S. Nowlin</writer>
        </credits>
        <description>Thomas vaknar upp instängd i en gigantisk, ständigt föränderlig labyrint
            tillsammans med en grupp andra pojkar. Han har inget minne av världen utanför förutom
            konstiga drömmar. Pojkarnas enda chans till överlevnad är att samarbeta.</description>
        <score>6.8</score>
        <rating>PG-13</rating>
        <production>
            <date>
                <year>2014</year>
                <month>09</month>
                <day>19</day>
            </date>
            <budget currency="USD">34 miljoner</budget>
            <country>USA</country>
            <country>Storbritannien</country>
        </production>
        <IMDb_website
            url="https://www.imdb.com/title/tt1790864/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_the%2520maze" />
    </movie>

    <movie>
        <title>Stalker</title>
        <credits>
            <director>Andrei Tarkovsky</director>
            <writer>Arkadiy Strugatskiy</writer>
            <writer>Boris Strugatskiy</writer>
            <writer>Andrei Tarkovsky</writer>
        </credits>
        <description>Stalkern arbetar som vägvisare och leder en författare och en vetenskapsman in
            i den mystiska Zonen, en plats där många underliga företeelser sker. I en bunker i Zonen
            sägs ett rum finnas som kan uppfylla alla ens innersta önskningar.</description>
        <score>8.1</score>
        <rating>Utan Etikett</rating>
        <production>
            <date>
                <year>1980</year>
                <month>04</month>
                <day>17</day>
            </date>
            <budget currency="RUB">1 miljon</budget>
            <country>Sovjetunionen</country>
        </production>
        <IMDb_website url="https://www.imdb.com/title/tt0079944/" />
    </movie>

</movieList>

=== HibbaHindawi/wt3/U1/movielist1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE movieList SYSTEM "movielist.dtd">

<movieList>

    <category>Skräck</category>

    <movie>
        <title>Insidious: The Red Door</title>
        <credits>
            <director>Patrick Wilson</director>
            <writer>Leigh Whannell</writer>
            <writer>Scott Teems</writer>
        </credits>
        <description>För att bekämpa sina demoner måste Josh och Dalton gå djupare in i The Further än någonsin tidigare, och möta sin familjs mörka och skrämmande ondska som lurar bakom den röda dörren.</description>
        <score>5.5</score>
        <rating>PG-13</rating>
        <production>
            <date>
                <year>2023</year>
                <month>07</month>
                <day>05</day>
            </date>
            <budget currency="USD">16 miljoner</budget>
            <country>USA</country>
            <country>Kanada</country>
        </production>
        <IMDb_website url="https://www.imdb.com/title/tt13405778/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_insidiou"/>
    </movie>

    <movie>
        <title>The Ring</title>
        <credits>
            <director>Gore Verbinski</director>
            <writer>Ehren Kruger</writer>
            <writer>Kôji Suzuki</writer>
            <writer>Hiroshi Takahashi</writer>
        </credits>
        <description>När fyra ungdomar dör sju dagar efter att ha tittat på ett videoband spårar en reporter upp bandet och tittar på det. Nu har hon sju dagar på sig att lösa mysteriet.</description>
        <score>7.1</score>
        <rating>PG-13</rating>
        <production>
            <date>
                <year>2003</year>
                <month>02</month>
                <day>21</day>
            </date>
            <budget currency="USD">48 miljoner</budget>
            <country>USA</country>
            <country>Japan</country>
        </production>
        <IMDb_website url="https://www.imdb.com/title/tt0298130/"/>
    </movie>

    <movie>
        <title>The Texas Chainsaw Massacre</title>
        <credits>
            <director>Marcus Nispel</director>
            <writer>Kim Henkel</writer>
            <writer>Tobe Hooper</writer>
            <writer>Scott Kosar</writer>
        </credits>
        <description>Ett gäng tonåringar är på bilsemester och förvillar sig av misstag in i en lada bebodd av kannibaler.</description>
        <score>6.2</score>
        <rating>R</rating>
        <production>
            <date>
                <year>2004</year>
                <month>01</month>
                <day>16</day>
            </date>
            <budget currency="USD">9,5 miljoner</budget>
            <country>USA</country>
        </production>
        <IMDb_website url="https://www.imdb.com/title/tt0324216/"/>
    </movie>

</movieList>
